# -*- coding: utf-8 -*-
"""Copia de vacuna_Alex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fw6W128cKruwEcGvz8AWb89iKEsJTpO0
"""


import os, sys
import pandas as pd

bbox = pd.read_csv('bbox_spain.txt')

import tweepy
consumer_key = "XXXXXXXXX"
consumer_secret = "XXXXXXXXXXXXXXXXXXXXXXXXXX"
access_token = "XXXXXXXXXXXXXXXXXXXXXXXXXX"
access_token_secret = "XXXXXXXXXXXXXXXXXXXXXXXXXX"

import pandas as pd
import preprocessor as p
import re
ca_df = pd.read_csv('bbox_spain.txt')

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

from geopy.geocoders import Nominatim
search= ['Vacuna covid' , 'vacuna coronavirus']
geolocator = Nominatim(user_agent="vacuna_Pablo")
my_path = os.getcwd()
my_path =my_path+'/Tweets/'
if not os.path.exists(my_path):
    os.makedirs(my_path)
    
for i in range(6,13):
  place = bbox['CA'][i]
  geo = geolocator.geocode(place)
  rad = bbox['Radius'][i]
  ruta = my_path+place+'.txt'
  geocode = str (geo.latitude) + ',' + str (geo.longitude) + ',' + str (rad) + 'km'
  for tweet in tweepy.Cursor(api.search, q=search, lang="es", geocode=geocode, tweet_mode='extended', include_rts=False).items(400):
    if (tweet.in_reply_to_status_id_str is None):
      f  = open(ruta, "a") 
      txt = re.sub("RT @[\w]*:","",tweet._json["full_text"])
      regrex_pattern = re.compile(pattern = "["
          u"\U0001F600-\U0001F64F"  # emoticons
          u"\U0001F300-\U0001F5FF"  # symbols & pictographs
          u"\U0001F680-\U0001F6FF"  # transport & map symbols
          u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                              "]+", flags = re.UNICODE)
      txt = regrex_pattern.sub(r'',txt)
      txt = re.sub("@[\w]*","",txt)
      txt = re.sub("https?://[A-Za-z0-9./]*","",txt)
      txt = re.sub("\n","",txt)    
      f.write(txt + '\n')
      f.close()

